### PR TITLE
Update Network Management

### PR DESCRIPTION
**Pull request by h0ngcha0**
1. Make it possible to update URLs for `Mainnet` (already possible to `Testnet` and `Devnet`)
2. Make it not possible to add extra custom networks. The reason is that it makes things complicated: a) custom network can not be connected with dApps which require one of the `devnet`, `testnet` or `mainnet` network. b) tokens in token list belong to one of `testnet` or `mainnet`. Due to these, custom network feature is probably not used that much. 
3. Make it possible to use `nodeAPIKey`
4. Remove temporary fix for displaying `000301` NFT since explorer backend `2.2.1` is now used.

There is already a button to reset to default network if user messes up the network settings.

### CODE REVIEW

**Comment by h0ngcha0** [comment]
Yes, please see the images below:

image
image
image

**Review by pragmaxim — APPROVED** [review]
LTGM :+1:

**Comment by polarker** [comment]
@h0ngcha0 It seems the reset icon is not aligned with the text next to it

**Comment by h0ngcha0** [comment]
> @h0ngcha0 It seems the reset icon is not aligned with the text next to it

Thanks, fixed now

image

**Review by Lbqds — APPROVED** [review]
LGTM 👍

**Comment by polarker** [comment]
LGTM. Let's release

**Pull request merged**
